//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProducto.productoServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/Indigowcf")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockMinimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrecioVenta {
            get {
                return this.PrecioVentaField;
            }
            set {
                if ((this.PrecioVentaField.Equals(value) != true)) {
                    this.PrecioVentaField = value;
                    this.RaisePropertyChanged("PrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockMaximo {
            get {
                return this.StockMaximoField;
            }
            set {
                if ((this.StockMaximoField.Equals(value) != true)) {
                    this.StockMaximoField = value;
                    this.RaisePropertyChanged("StockMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockMinimo {
            get {
                return this.StockMinimoField;
            }
            set {
                if ((this.StockMinimoField.Equals(value) != true)) {
                    this.StockMinimoField = value;
                    this.RaisePropertyChanged("StockMinimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="productoServiceRef.IProductoService")]
    public interface IProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/nuevoProducto", ReplyAction="http://tempuri.org/IProductoService/nuevoProductoResponse")]
        int nuevoProducto(WebAppProducto.productoServiceRef.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/nuevoProducto", ReplyAction="http://tempuri.org/IProductoService/nuevoProductoResponse")]
        System.Threading.Tasks.Task<int> nuevoProductoAsync(WebAppProducto.productoServiceRef.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/editarProducto", ReplyAction="http://tempuri.org/IProductoService/editarProductoResponse")]
        int editarProducto(WebAppProducto.productoServiceRef.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/editarProducto", ReplyAction="http://tempuri.org/IProductoService/editarProductoResponse")]
        System.Threading.Tasks.Task<int> editarProductoAsync(WebAppProducto.productoServiceRef.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/eliminarProducto", ReplyAction="http://tempuri.org/IProductoService/eliminarProductoResponse")]
        int eliminarProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/eliminarProducto", ReplyAction="http://tempuri.org/IProductoService/eliminarProductoResponse")]
        System.Threading.Tasks.Task<int> eliminarProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/buscarProducto", ReplyAction="http://tempuri.org/IProductoService/buscarProductoResponse")]
        WebAppProducto.productoServiceRef.Producto buscarProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/buscarProducto", ReplyAction="http://tempuri.org/IProductoService/buscarProductoResponse")]
        System.Threading.Tasks.Task<WebAppProducto.productoServiceRef.Producto> buscarProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/consultarProducto", ReplyAction="http://tempuri.org/IProductoService/consultarProductoResponse")]
        System.Data.DataTable consultarProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/consultarProducto", ReplyAction="http://tempuri.org/IProductoService/consultarProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> consultarProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/mostrarProductos", ReplyAction="http://tempuri.org/IProductoService/mostrarProductosResponse")]
        WebAppProducto.productoServiceRef.Producto[] mostrarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/mostrarProductos", ReplyAction="http://tempuri.org/IProductoService/mostrarProductosResponse")]
        System.Threading.Tasks.Task<WebAppProducto.productoServiceRef.Producto[]> mostrarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServiceChannel : WebAppProducto.productoServiceRef.IProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServiceClient : System.ServiceModel.ClientBase<WebAppProducto.productoServiceRef.IProductoService>, WebAppProducto.productoServiceRef.IProductoService {
        
        public ProductoServiceClient() {
        }
        
        public ProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int nuevoProducto(WebAppProducto.productoServiceRef.Producto producto) {
            return base.Channel.nuevoProducto(producto);
        }
        
        public System.Threading.Tasks.Task<int> nuevoProductoAsync(WebAppProducto.productoServiceRef.Producto producto) {
            return base.Channel.nuevoProductoAsync(producto);
        }
        
        public int editarProducto(WebAppProducto.productoServiceRef.Producto producto) {
            return base.Channel.editarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<int> editarProductoAsync(WebAppProducto.productoServiceRef.Producto producto) {
            return base.Channel.editarProductoAsync(producto);
        }
        
        public int eliminarProducto(int idProducto) {
            return base.Channel.eliminarProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<int> eliminarProductoAsync(int idProducto) {
            return base.Channel.eliminarProductoAsync(idProducto);
        }
        
        public WebAppProducto.productoServiceRef.Producto buscarProducto(int idProducto) {
            return base.Channel.buscarProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<WebAppProducto.productoServiceRef.Producto> buscarProductoAsync(int idProducto) {
            return base.Channel.buscarProductoAsync(idProducto);
        }
        
        public System.Data.DataTable consultarProducto() {
            return base.Channel.consultarProducto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> consultarProductoAsync() {
            return base.Channel.consultarProductoAsync();
        }
        
        public WebAppProducto.productoServiceRef.Producto[] mostrarProductos() {
            return base.Channel.mostrarProductos();
        }
        
        public System.Threading.Tasks.Task<WebAppProducto.productoServiceRef.Producto[]> mostrarProductosAsync() {
            return base.Channel.mostrarProductosAsync();
        }
    }
}
