//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProducto.remisionServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Remision", Namespace="http://schemas.datacontract.org/2004/07/Indigowcf")]
    [System.SerializableAttribute()]
    public partial class Remision : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProveedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlmacen {
            get {
                return this.IdAlmacenField;
            }
            set {
                if ((this.IdAlmacenField.Equals(value) != true)) {
                    this.IdAlmacenField = value;
                    this.RaisePropertyChanged("IdAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProveedor {
            get {
                return this.IdProveedorField;
            }
            set {
                if ((this.IdProveedorField.Equals(value) != true)) {
                    this.IdProveedorField = value;
                    this.RaisePropertyChanged("IdProveedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemisionDetalle", Namespace="http://schemas.datacontract.org/2004/07/Indigowcf")]
    [System.SerializableAttribute()]
    public partial class RemisionDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRemisionEntradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRemisionEntrada {
            get {
                return this.IdRemisionEntradaField;
            }
            set {
                if ((this.IdRemisionEntradaField.Equals(value) != true)) {
                    this.IdRemisionEntradaField = value;
                    this.RaisePropertyChanged("IdRemisionEntrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="remisionServiceRef.IRemisionService")]
    public interface IRemisionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/nuevaRemision", ReplyAction="http://tempuri.org/IRemisionService/nuevaRemisionResponse")]
        int nuevaRemision(WebAppProducto.remisionServiceRef.Remision remision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/nuevaRemision", ReplyAction="http://tempuri.org/IRemisionService/nuevaRemisionResponse")]
        System.Threading.Tasks.Task<int> nuevaRemisionAsync(WebAppProducto.remisionServiceRef.Remision remision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/actualizarEstado", ReplyAction="http://tempuri.org/IRemisionService/actualizarEstadoResponse")]
        int actualizarEstado(WebAppProducto.remisionServiceRef.Remision remision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/actualizarEstado", ReplyAction="http://tempuri.org/IRemisionService/actualizarEstadoResponse")]
        System.Threading.Tasks.Task<int> actualizarEstadoAsync(WebAppProducto.remisionServiceRef.Remision remision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/nuevaRemisionEntrada", ReplyAction="http://tempuri.org/IRemisionService/nuevaRemisionEntradaResponse")]
        int nuevaRemisionEntrada(WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/nuevaRemisionEntrada", ReplyAction="http://tempuri.org/IRemisionService/nuevaRemisionEntradaResponse")]
        System.Threading.Tasks.Task<int> nuevaRemisionEntradaAsync(WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/actualizarInventarioFisico", ReplyAction="http://tempuri.org/IRemisionService/actualizarInventarioFisicoResponse")]
        int actualizarInventarioFisico(WebAppProducto.remisionServiceRef.Remision remision, WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/actualizarInventarioFisico", ReplyAction="http://tempuri.org/IRemisionService/actualizarInventarioFisicoResponse")]
        System.Threading.Tasks.Task<int> actualizarInventarioFisicoAsync(WebAppProducto.remisionServiceRef.Remision remision, WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/buscarRemision", ReplyAction="http://tempuri.org/IRemisionService/buscarRemisionResponse")]
        WebAppProducto.remisionServiceRef.Remision buscarRemision(int idRemision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/buscarRemision", ReplyAction="http://tempuri.org/IRemisionService/buscarRemisionResponse")]
        System.Threading.Tasks.Task<WebAppProducto.remisionServiceRef.Remision> buscarRemisionAsync(int idRemision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/suma", ReplyAction="http://tempuri.org/IRemisionService/sumaResponse")]
        int suma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemisionService/suma", ReplyAction="http://tempuri.org/IRemisionService/sumaResponse")]
        System.Threading.Tasks.Task<int> sumaAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemisionServiceChannel : WebAppProducto.remisionServiceRef.IRemisionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemisionServiceClient : System.ServiceModel.ClientBase<WebAppProducto.remisionServiceRef.IRemisionService>, WebAppProducto.remisionServiceRef.IRemisionService {
        
        public RemisionServiceClient() {
        }
        
        public RemisionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemisionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemisionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemisionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int nuevaRemision(WebAppProducto.remisionServiceRef.Remision remision) {
            return base.Channel.nuevaRemision(remision);
        }
        
        public System.Threading.Tasks.Task<int> nuevaRemisionAsync(WebAppProducto.remisionServiceRef.Remision remision) {
            return base.Channel.nuevaRemisionAsync(remision);
        }
        
        public int actualizarEstado(WebAppProducto.remisionServiceRef.Remision remision) {
            return base.Channel.actualizarEstado(remision);
        }
        
        public System.Threading.Tasks.Task<int> actualizarEstadoAsync(WebAppProducto.remisionServiceRef.Remision remision) {
            return base.Channel.actualizarEstadoAsync(remision);
        }
        
        public int nuevaRemisionEntrada(WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle) {
            return base.Channel.nuevaRemisionEntrada(remisiondetalle);
        }
        
        public System.Threading.Tasks.Task<int> nuevaRemisionEntradaAsync(WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle) {
            return base.Channel.nuevaRemisionEntradaAsync(remisiondetalle);
        }
        
        public int actualizarInventarioFisico(WebAppProducto.remisionServiceRef.Remision remision, WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle) {
            return base.Channel.actualizarInventarioFisico(remision, remisiondetalle);
        }
        
        public System.Threading.Tasks.Task<int> actualizarInventarioFisicoAsync(WebAppProducto.remisionServiceRef.Remision remision, WebAppProducto.remisionServiceRef.RemisionDetalle remisiondetalle) {
            return base.Channel.actualizarInventarioFisicoAsync(remision, remisiondetalle);
        }
        
        public WebAppProducto.remisionServiceRef.Remision buscarRemision(int idRemision) {
            return base.Channel.buscarRemision(idRemision);
        }
        
        public System.Threading.Tasks.Task<WebAppProducto.remisionServiceRef.Remision> buscarRemisionAsync(int idRemision) {
            return base.Channel.buscarRemisionAsync(idRemision);
        }
        
        public int suma(int x, int y) {
            return base.Channel.suma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> sumaAsync(int x, int y) {
            return base.Channel.sumaAsync(x, y);
        }
    }
}
